-- 5.1 Validate expected objects exist
USE ROLE ACCOUNTADMIN;

SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE();

SHOW USERS LIKE 'DP_MAILBLAZE_DEMO_ADMIN';
SHOW ROLES LIKE 'DP_MAILBLAZE_DEMO_DEV_ROLE_%';
SHOW WAREHOUSES LIKE 'DP_MAILBLAZE_DEMO_DEV_WH_%';

-- Also check DB presence
SHOW DATABASES LIKE 'DP_MAILBLAZE_DEMO_DEV_DB';