-- 5.2 Bootstrap RBAC and warehouses
USE ROLE ACCOUNTADMIN;

SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE();

-- Roles
CREATE ROLE IF NOT EXISTS DP_MAILBLAZE_DEMO_ADMIN;
CREATE ROLE IF NOT EXISTS DP_MAILBLAZE_DEMO_DEV_ROLE_INGEST;
CREATE ROLE IF NOT EXISTS DP_MAILBLAZE_DEMO_DEV_ROLE_TRANSFORM;
CREATE ROLE IF NOT EXISTS DP_MAILBLAZE_DEMO_DEV_ROLE_BI;

-- Role hierarchy
GRANT ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_INGEST    TO ROLE DP_MAILBLAZE_DEMO_ADMIN;
GRANT ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_TRANSFORM TO ROLE DP_MAILBLAZE_DEMO_ADMIN;
GRANT ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_BI        TO ROLE DP_MAILBLAZE_DEMO_ADMIN;

-- User (project admin user)
-- REPLACEMENT REQUIRED: replace the PASSWORD string with your generated password.
CREATE USER IF NOT EXISTS DP_MAILBLAZE_DEMO_ADMIN
  LOGIN_NAME = 'DP_MAILBLAZE_DEMO_ADMIN'
  DISPLAY_NAME = 'DP Mailblaze Demo Admin'
  DEFAULT_ROLE = DP_MAILBLAZE_DEMO_ADMIN
  MUST_CHANGE_PASSWORD = FALSE
  PASSWORD = 'za';

GRANT ROLE DP_MAILBLAZE_DEMO_ADMIN TO USER DP_MAILBLAZE_DEMO_ADMIN;

-- Warehouses (cost-conscious)
CREATE WAREHOUSE IF NOT EXISTS DP_MAILBLAZE_DEMO_DEV_WH_INGEST
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS DP_MAILBLAZE_DEMO_DEV_WH_TRANSFORM
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS DP_MAILBLAZE_DEMO_DEV_WH_BI
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Warehouse grants
GRANT USAGE, OPERATE ON WAREHOUSE DP_MAILBLAZE_DEMO_DEV_WH_INGEST    TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_INGEST;
GRANT USAGE, OPERATE ON WAREHOUSE DP_MAILBLAZE_DEMO_DEV_WH_TRANSFORM TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_TRANSFORM;
GRANT USAGE, OPERATE ON WAREHOUSE DP_MAILBLAZE_DEMO_DEV_WH_BI        TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_BI;

-- Admin can use all warehouses
GRANT USAGE, OPERATE ON WAREHOUSE DP_MAILBLAZE_DEMO_DEV_WH_INGEST    TO ROLE DP_MAILBLAZE_DEMO_ADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE DP_MAILBLAZE_DEMO_DEV_WH_TRANSFORM TO ROLE DP_MAILBLAZE_DEMO_ADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE DP_MAILBLAZE_DEMO_DEV_WH_BI        TO ROLE DP_MAILBLAZE_DEMO_ADMIN;