-- 5.3 DB + schemas + grants
USE ROLE DP_MAILBLAZE_DEMO_ADMIN;
USE WAREHOUSE DP_MAILBLAZE_DEMO_DEV_WH_TRANSFORM;

SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE();

CREATE DATABASE IF NOT EXISTS DP_MAILBLAZE_DEMO_DEV_DB;

CREATE SCHEMA IF NOT EXISTS DP_MAILBLAZE_DEMO_DEV_DB.RAW;
CREATE SCHEMA IF NOT EXISTS DP_MAILBLAZE_DEMO_DEV_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS DP_MAILBLAZE_DEMO_DEV_DB.MARTS;
CREATE SCHEMA IF NOT EXISTS DP_MAILBLAZE_DEMO_DEV_DB.SECURITY;

-- Database usage
GRANT USAGE ON DATABASE DP_MAILBLAZE_DEMO_DEV_DB TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_INGEST;
GRANT USAGE ON DATABASE DP_MAILBLAZE_DEMO_DEV_DB TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_TRANSFORM;
GRANT USAGE ON DATABASE DP_MAILBLAZE_DEMO_DEV_DB TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_BI;

-- Schema usage
GRANT USAGE ON SCHEMA DP_MAILBLAZE_DEMO_DEV_DB.RAW      TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_INGEST;
GRANT USAGE ON SCHEMA DP_MAILBLAZE_DEMO_DEV_DB.STAGING  TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_TRANSFORM;
GRANT USAGE ON SCHEMA DP_MAILBLAZE_DEMO_DEV_DB.MARTS    TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_BI;
GRANT USAGE ON SCHEMA DP_MAILBLAZE_DEMO_DEV_DB.SECURITY TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_TRANSFORM;

-- Create privileges
GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA DP_MAILBLAZE_DEMO_DEV_DB.RAW TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_INGEST;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA DP_MAILBLAZE_DEMO_DEV_DB.STAGING TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_TRANSFORM;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA DP_MAILBLAZE_DEMO_DEV_DB.MARTS   TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_TRANSFORM;

-- BI read access on MARTS (present + future)
GRANT SELECT ON ALL TABLES IN SCHEMA DP_MAILBLAZE_DEMO_DEV_DB.MARTS TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_BI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DP_MAILBLAZE_DEMO_DEV_DB.MARTS TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_BI;
GRANT SELECT ON ALL VIEWS IN SCHEMA DP_MAILBLAZE_DEMO_DEV_DB.MARTS TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_BI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DP_MAILBLAZE_DEMO_DEV_DB.MARTS TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_BI;