USE ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_INGEST;
USE WAREHOUSE DP_MAILBLAZE_DEMO_DEV_WH_INGEST;

SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE();

USE DATABASE DP_MAILBLAZE_DEMO_DEV_DB;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS FF_JSON
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

CREATE FILE FORMAT IF NOT EXISTS FF_CSV
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null');

CREATE STAGE IF NOT EXISTS STG_S3_RAW
  URL = 's3://dp-mailblaze-demo-dev-raw-3dfbc1/'
  STORAGE_INTEGRATION = DP_MAILBLAZE_DEMO_DEV_S3_INT
  FILE_FORMAT = FF_JSON;

-- This is the critical proof: must return objects without sts:AssumeRole failures
LIST @STG_S3_RAW;

CREATE TABLE IF NOT EXISTS RAW.EMAIL_EVENTS_RAW (
  ingested_at TIMESTAMP_NTZ,
  source_file STRING,
  payload VARIANT
);

CREATE TABLE IF NOT EXISTS RAW.INVENTORY_RAW (
  ingested_at TIMESTAMP_NTZ,
  source_file STRING,
  sku STRING,
  warehouse_id STRING,
  on_hand NUMBER,
  as_of_date DATE
);

COPY INTO RAW.EMAIL_EVENTS_RAW (ingested_at, source_file, payload)
FROM (
  SELECT
    CURRENT_TIMESTAMP(),
    METADATA$FILENAME,
    PARSE_JSON($1)
  FROM @STG_S3_RAW/events/
)
FILE_FORMAT = (TYPE=JSON)
PATTERN = '.*\\.jsonl$'
ON_ERROR = 'CONTINUE';

COPY INTO RAW.INVENTORY_RAW (ingested_at, source_file, sku, warehouse_id, on_hand, as_of_date)
FROM (
  SELECT
    CURRENT_TIMESTAMP(),
    METADATA$FILENAME,
    $1::STRING,
    $2::STRING,
    $3::NUMBER,
    $4::DATE
  FROM @STG_S3_RAW/inventory/
)
FILE_FORMAT = (FORMAT_NAME=RAW.FF_CSV)
PATTERN = '.*\\.csv$'
ON_ERROR = 'ABORT_STATEMENT';