USE ROLE DP_MAILBLAZE_DEMO_ADMIN;
USE WAREHOUSE DP_MAILBLAZE_DEMO_DEV_WH_TRANSFORM;

SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE();

USE DATABASE DP_MAILBLAZE_DEMO_DEV_DB;

USE SCHEMA SECURITY;

CREATE TABLE IF NOT EXISTS DP_MAILBLAZE_DEMO_DEV_DB.SECURITY.REGION_ACCESS (
  role_name STRING,
  allowed_region STRING
);

MERGE INTO DP_MAILBLAZE_DEMO_DEV_DB.SECURITY.REGION_ACCESS t
USING (SELECT 'DP_MAILBLAZE_DEMO_DEV_ROLE_BI' AS role_name, 'EU' AS allowed_region) s
ON t.role_name = s.role_name AND t.allowed_region = s.allowed_region
WHEN NOT MATCHED THEN INSERT (role_name, allowed_region) VALUES (s.role_name, s.allowed_region);

CREATE OR REPLACE ROW ACCESS POLICY DP_MAILBLAZE_DEMO_DEV_DB.SECURITY.RAP_REGION_FILTER
AS (region STRING) RETURNS BOOLEAN ->
  EXISTS (
    SELECT 1
    FROM DP_MAILBLAZE_DEMO_DEV_DB.SECURITY.REGION_ACCESS ra
    WHERE ra.role_name = CURRENT_ROLE()
      AND ra.allowed_region = region
  );

USE SCHEMA MARTS;

CREATE TABLE IF NOT EXISTS DP_MAILBLAZE_DEMO_DEV_DB.MARTS.DIM_CUSTOMER_SECURE (
  customer_id STRING,
  email STRING,
  region STRING
);

MERGE INTO DP_MAILBLAZE_DEMO_DEV_DB.MARTS.DIM_CUSTOMER_SECURE t
USING (SELECT 'CUST_001' AS customer_id, 'alice@example.com' AS email, 'EU' AS region) s
ON t.customer_id = s.customer_id
WHEN NOT MATCHED THEN INSERT (customer_id, email, region) VALUES (s.customer_id, s.email, s.region);

MERGE INTO DP_MAILBLAZE_DEMO_DEV_DB.MARTS.DIM_CUSTOMER_SECURE t
USING (SELECT 'CUST_002' AS customer_id, 'bob@example.com' AS email, 'US' AS region) s
ON t.customer_id = s.customer_id
WHEN NOT MATCHED THEN INSERT (customer_id, email, region) VALUES (s.customer_id, s.email, s.region);

ALTER TABLE DP_MAILBLAZE_DEMO_DEV_DB.MARTS.DIM_CUSTOMER_SECURE
  DROP ROW ACCESS POLICY DP_MAILBLAZE_DEMO_DEV_DB.SECURITY.RAP_REGION_FILTER;

ALTER TABLE DP_MAILBLAZE_DEMO_DEV_DB.MARTS.DIM_CUSTOMER_SECURE
  ADD ROW ACCESS POLICY DP_MAILBLAZE_DEMO_DEV_DB.SECURITY.RAP_REGION_FILTER ON (region);

CREATE OR REPLACE SECURE VIEW DP_MAILBLAZE_DEMO_DEV_DB.MARTS.VW_DIM_CUSTOMER_SECURE AS
SELECT customer_id, email, region
FROM DP_MAILBLAZE_DEMO_DEV_DB.MARTS.DIM_CUSTOMER_SECURE;

GRANT USAGE ON DATABASE DP_MAILBLAZE_DEMO_DEV_DB TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_BI;
GRANT USAGE ON SCHEMA DP_MAILBLAZE_DEMO_DEV_DB.MARTS TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_BI;
GRANT SELECT ON VIEW DP_MAILBLAZE_DEMO_DEV_DB.MARTS.VW_DIM_CUSTOMER_SECURE TO ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_BI;