-- Validate objects exist
USE ROLE ACCOUNTADMIN;

SHOW USERS LIKE 'DP_MAILBLAZE_DEMO_ADMIN';
SHOW ROLES LIKE 'DP_MAILBLAZE_DEMO_DEV_ROLE_%';
SHOW WAREHOUSES LIKE 'DP_MAILBLAZE_DEMO_DEV_WH_%';
SHOW DATABASES LIKE 'DP_MAILBLAZE_DEMO_DEV_DB';

SHOW INTEGRATIONS LIKE 'DP_MAILBLAZE_DEMO_DEV_S3_INT';

-- Verify stage access
USE ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_INGEST;
USE WAREHOUSE DP_MAILBLAZE_DEMO_DEV_WH_INGEST;
SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE();

USE DATABASE DP_MAILBLAZE_DEMO_DEV_DB;
USE SCHEMA RAW;

SHOW STAGES LIKE 'STG_S3_RAW';
LIST @STG_S3_RAW;

SELECT COUNT(*) AS email_events_raw_rows FROM RAW.EMAIL_EVENTS_RAW;
SELECT COUNT(*) AS inventory_raw_rows FROM RAW.INVENTORY_RAW;

-- Verify RLS secure view works for BI
USE ROLE DP_MAILBLAZE_DEMO_DEV_ROLE_BI;
USE WAREHOUSE DP_MAILBLAZE_DEMO_DEV_WH_BI;
SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE();

USE DATABASE DP_MAILBLAZE_DEMO_DEV_DB;
USE SCHEMA MARTS;

SHOW VIEWS LIKE 'VW_DIM_CUSTOMER_SECURE';
SELECT * FROM VW_DIM_CUSTOMER_SECURE;